<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="surefire.MyTest" time="0" tests="1" errors="1" skipped="0" failures="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
  </properties>
  <testcase name="test" classname="surefire.MyTest" time="0">
    <error message="java.lang.IndexOutOfBoundsException" type="java.lang.RuntimeException">java.lang.RuntimeException: java.lang.IndexOutOfBoundsException
	at surefire.MyTest.rethrownDelegate(MyTest.java:24)
	at surefire.MyTest.newRethrownDelegate(MyTest.java:17)
	at surefire.MyTest.test(MyTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:167)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:147)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:130)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:211)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:163)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:105)
	Caused by: java.lang.IndexOutOfBoundsException
	at surefire.MyTest.failure(MyTest.java:33)
	at surefire.MyTest.access$100(MyTest.java:9)
	at surefire.MyTest$Nested.run(MyTest.java:38)
	at surefire.MyTest.delegate(MyTest.java:29)
	at surefire.MyTest.rethrownDelegate(MyTest.java:22)
</error>
  </testcase>
</testsuite>